#!/usr/bin/env bash
# Detect whether cwd is a git repo. If so, emit the path-privacy directive(s)
# as additionalContext so Claude has the rule loaded.

CWD=$(jq -r '.cwd // ""' 2>/dev/null)

if [ -z "$CWD" ] || [ ! -d "$CWD" ]; then
  exit 0
fi

# Only inject when inside a git working tree
if ! git -C "$CWD" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  exit 0
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONTEXT=""

# --- outdated-wrapper notice -------------------------------------------------
# A plugin update refreshes the scanner the wrapper CALLS, but not the wrapper
# itself -- its logic is baked in at install time. So a repo can quietly carry a
# wrapper whose bugs were fixed several releases ago, with nothing to reveal it:
# before 0.6.0 the generated file had no version marker at all, so old and new
# were indistinguishable by inspection.
#
# This tells you once, per repo, in the repo where it matters. It deliberately
# does NOT rewrite the hook: silently editing a file in someone's .git/hooks at
# session start is exactly the kind of surprise a privacy gate should never
# spring, and the same install path had four repo-damaging bugs before 0.6.0.
HOOKS_DIR=$(git -C "$CWD" rev-parse --path-format=absolute --git-path hooks 2>/dev/null || echo "")
CURRENT_VERSION=$(sed -n 's/.*"version"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' \
                  "$SCRIPT_DIR/../.claude-plugin/plugin.json" 2>/dev/null | head -1)
STALE_HOOKS=""
if [ -n "$HOOKS_DIR" ] && [ -n "$CURRENT_VERSION" ]; then
  for h in pre-commit commit-msg; do
    f="$HOOKS_DIR/$h"
    [ -f "$f" ] || continue
    grep -q 'path-privacy:wrapper' "$f" 2>/dev/null || continue
    have=$(sed -n 's/^# path-privacy:wrapper-version //p' "$f" | head -1)
    [ -z "$have" ] && have="pre-0.6.0"
    if [ "$have" != "$CURRENT_VERSION" ]; then
      STALE_HOOKS="${STALE_HOOKS:+$STALE_HOOKS, }$h ($have)"
    fi
  done
fi
if [ -n "$STALE_HOOKS" ]; then
  CONTEXT+="path-privacy: this repo's git hooks were generated by an older version of the plugin"
  CONTEXT+=$' \u2014 '"$STALE_HOOKS; current is $CURRENT_VERSION."$'\n'
  CONTEXT+="Their logic is frozen at install time, so a plugin update does not refresh it."$'\n'
  CONTEXT+="Re-run install-git-hooks.sh in this repo (or /path-privacy:path-privacy) to update them."$'\n'
  CONTEXT+="Mention this to the user once, then carry on; do not rewrite the hooks yourself."$'\n'
fi
# -----------------------------------------------------------------------------

# Each directive file has "# trigger: <signal>" on line 1. Trigger 'git' fires
# when inside a git repo (the check above already enforced this). Other triggers
# can be added later (e.g., 'history' if a leak in history is detected).
for f in "$SCRIPT_DIR"/directives/*.md; do
  [ -f "$f" ] || continue
  trigger=$(head -1 "$f" | sed 's/^# trigger: //')
  case "$trigger" in
    git|any) ;;
    *)        continue ;;
  esac
  [ -n "$CONTEXT" ] && CONTEXT+=$'\n'
  CONTEXT+=$(tail -n +2 "$f")
done

[ -z "$CONTEXT" ] && exit 0

JSON_CONTEXT=$(printf '%s' "$CONTEXT" | jq -Rs '.')

cat <<EOF
{
  "hookSpecificOutput": {
    "hookEventName": "SessionStart",
    "additionalContext": ${JSON_CONTEXT}
  }
}
EOF

exit 0
