#!/usr/bin/env bash
# path-privacy: skip-file
# install-git-hooks.sh - install path-privacy git hooks into a repo.
#
# Default behavior: install pre-commit and commit-msg hooks that delegate to the
# scanner. If a hook already exists, the existing hook is preserved by being
# moved to <hook>.local and the new wrapper invokes it first, then runs the
# path-privacy check.
#
# Usage:
#   install-git-hooks.sh                      # install into the current repo
#   install-git-hooks.sh -C <path-to-repo>    # install into a different repo
#   install-git-hooks.sh --uninstall          # restore .local backups, remove wrappers

set -eu

TARGET_REPO=""
UNINSTALL=0

while [ $# -gt 0 ]; do
  case "$1" in
    -C|--cwd)       TARGET_REPO="$2"; shift 2 ;;
    --uninstall)    UNINSTALL=1; shift ;;
    -h|--help)      sed -n '2,12p' "$0"; exit 0 ;;
    *) echo "install-git-hooks: unknown arg: $1" >&2; exit 2 ;;
  esac
done

if [ -z "$TARGET_REPO" ]; then
  TARGET_REPO=$(git rev-parse --show-toplevel 2>/dev/null || echo "")
fi
if [ -z "$TARGET_REPO" ] || [ ! -d "$TARGET_REPO/.git" ]; then
  echo "install-git-hooks: not a git repo (or .git missing): $TARGET_REPO" >&2
  exit 2
fi

HOOKS_DIR="$TARGET_REPO/.git/hooks"
mkdir -p "$HOOKS_DIR"

SELF_DIR="$(cd "$(dirname "$0")" && pwd)"

uninstall_one() {
  local name="$1"
  local hook="$HOOKS_DIR/$name"
  local backup="$hook.local"
  if [ -f "$backup" ]; then
    mv "$backup" "$hook"
    echo "restored $hook from $backup"
  elif [ -f "$hook" ] && grep -q 'path-privacy:wrapper' "$hook" 2>/dev/null; then
    rm -f "$hook"
    echo "removed $hook"
  else
    echo "no path-privacy wrapper at $hook (nothing to do)"
  fi
}

if [ $UNINSTALL -eq 1 ]; then
  uninstall_one pre-commit
  uninstall_one commit-msg
  exit 0
fi

install_wrapper() {
  local name="$1"          # pre-commit | commit-msg
  local source_script="$2" # absolute path to the path-privacy script
  local hook="$HOOKS_DIR/$name"
  local backup="$hook.local"

  # If an existing hook is present and is NOT a path-privacy wrapper, back it up.
  if [ -f "$hook" ] && ! grep -q 'path-privacy:wrapper' "$hook" 2>/dev/null; then
    if [ ! -f "$backup" ]; then
      cp "$hook" "$backup"
      chmod +x "$backup"
      echo "preserved existing $hook -> $backup"
    fi
  fi

  cat > "$hook" <<EOF
#!/usr/bin/env bash
# path-privacy:wrapper -- generated by install-git-hooks.sh. Edit .local file instead.
set -u
HOOK_DIR="\$(cd "\$(dirname "\$0")" && pwd)"
HOOK_NAME="$(basename "$hook")"
LOCAL_HOOK="\$HOOK_DIR/\$HOOK_NAME.local"
SCRIPT_NAME="$(basename "$source_script")"
PATH_PRIVACY_SCRIPT="$source_script"

# Run the pre-existing hook first, if any.
if [ -x "\$LOCAL_HOOK" ]; then
  "\$LOCAL_HOOK" "\$@" || exit \$?
fi

# The path above is frozen at install time. For a marketplace install it points
# into the VERSION-STAMPED plugin cache: an update writes a new version dir and
# orphans the old one, deleted 14 days later, so the path dies on a 14-day fuse.
# Re-resolve to the newest copy. sort -V, not last-wins over glob order, which is
# lexicographic and would pick 0.1.9 over 0.1.10.
if [ ! -x "\$PATH_PRIVACY_SCRIPT" ]; then
  # Search the frozen path's own tree first, so a LOCAL checkout or --plugin-dir
  # install (whose scripts never live under the plugin cache) can still recover.
  FROZEN_ROOT="\${PATH_PRIVACY_SCRIPT%/skills/path-privacy/scripts/*}"
  PATH_PRIVACY_SCRIPT="\$(ls -1 \\
      "\${FROZEN_ROOT%/*}"/*/skills/path-privacy/scripts/"\$SCRIPT_NAME" \\
      "\$FROZEN_ROOT"/skills/path-privacy/scripts/"\$SCRIPT_NAME" \\
      "\$HOME"/.claude/plugins/cache/*/path-privacy/*/skills/path-privacy/scripts/"\$SCRIPT_NAME" \\
      2>/dev/null | sort -V | tail -1)"
fi

# Fail CLOSED and loudly. This hook is a leak gate; if it cannot run, allowing
# the commit silently is the worst outcome -- that is how a gate becomes
# decorative without anyone noticing.
if [ ! -x "\$PATH_PRIVACY_SCRIPT" ]; then
  echo "path-privacy: scanner not found -- the leak gate is NOT running." >&2
  echo "" >&2
  echo "  Why now: this usually means the plugin was updated and the old cached" >&2
  echo "  copy has since been cleaned up. It fires on the next commit after that," >&2
  echo "  which is why it looks unrelated to what you are committing." >&2
  echo "" >&2
  echo "  Looked for: \$SCRIPT_NAME under" >&2
  echo "    \${FROZEN_ROOT:-<install dir>}/ and \$HOME/.claude/plugins/cache/*/path-privacy/*/" >&2
  echo "  Reinstall:  /path-privacy:path-privacy   (or re-run install-git-hooks.sh)" >&2
  if [ -f "\$LOCAL_HOOK" ]; then
    # This wrapper CHAINS your previous hook. Deleting it would silently drop
    # that hook too, so restore it rather than remove the wrapper.
    echo "  Remove:     mv \$LOCAL_HOOK \$HOOK_DIR/\$HOOK_NAME" >&2
    echo "              (restores the \$HOOK_NAME hook you had before path-privacy)" >&2
  else
    echo "  Remove:     rm \$HOOK_DIR/\$HOOK_NAME" >&2
  fi
  exit 1
fi

"\$PATH_PRIVACY_SCRIPT" "\$@" || exit \$?
exit 0
EOF
  chmod +x "$hook"
  echo "installed $hook"
}

install_wrapper pre-commit "$SELF_DIR/git-pre-commit"
install_wrapper commit-msg "$SELF_DIR/git-commit-msg"

echo ""
echo "path-privacy hooks installed in $TARGET_REPO."
echo "To uninstall: $0 --uninstall"
