#!/usr/bin/env bash
# path-privacy: skip-file
# install-git-hooks.sh - install path-privacy git hooks into a repo.
#
# Default behavior: install pre-commit and commit-msg hooks that delegate to the
# scanner. If a hook already exists, the existing hook is preserved by being
# moved to <hook>.local and the new wrapper invokes it first, then runs the
# path-privacy check.
#
# Usage:
#   install-git-hooks.sh                      # install into the current repo
#   install-git-hooks.sh -C <path-to-repo>    # install into a different repo
#   install-git-hooks.sh --uninstall          # restore .local backups, remove wrappers

set -eu

TARGET_REPO=""
UNINSTALL=0

while [ $# -gt 0 ]; do
  case "$1" in
    -C|--cwd)       TARGET_REPO="$2"; shift 2 ;;
    --uninstall)    UNINSTALL=1; shift ;;
    -h|--help)      sed -n '2,12p' "$0"; exit 0 ;;
    *) echo "install-git-hooks: unknown arg: $1" >&2; exit 2 ;;
  esac
done

if [ -z "$TARGET_REPO" ]; then
  TARGET_REPO=$(git rev-parse --show-toplevel 2>/dev/null || echo "")
fi
if [ -z "$TARGET_REPO" ] || [ ! -d "$TARGET_REPO/.git" ]; then
  echo "install-git-hooks: not a git repo (or .git missing): $TARGET_REPO" >&2
  exit 2
fi

HOOKS_DIR="$TARGET_REPO/.git/hooks"
mkdir -p "$HOOKS_DIR"

SELF_DIR="$(cd "$(dirname "$0")" && pwd)"

uninstall_one() {
  local name="$1"
  local hook="$HOOKS_DIR/$name"
  local backup="$hook.local"
  if [ -f "$backup" ]; then
    mv "$backup" "$hook"
    echo "restored $hook from $backup"
  elif [ -f "$hook" ] && grep -q 'path-privacy:wrapper' "$hook" 2>/dev/null; then
    rm -f "$hook"
    echo "removed $hook"
  else
    echo "no path-privacy wrapper at $hook (nothing to do)"
  fi
}

if [ $UNINSTALL -eq 1 ]; then
  uninstall_one pre-commit
  uninstall_one commit-msg
  exit 0
fi

install_wrapper() {
  local name="$1"          # pre-commit | commit-msg
  local source_script="$2" # absolute path to the path-privacy script
  local hook="$HOOKS_DIR/$name"
  local backup="$hook.local"

  # If an existing hook is present and is NOT a path-privacy wrapper, back it up.
  if [ -f "$hook" ] && ! grep -q 'path-privacy:wrapper' "$hook" 2>/dev/null; then
    if [ ! -f "$backup" ]; then
      cp "$hook" "$backup"
      chmod +x "$backup"
      echo "preserved existing $hook -> $backup"
    fi
  fi

  cat > "$hook" <<EOF
#!/usr/bin/env bash
# path-privacy:wrapper -- generated by install-git-hooks.sh. Edit .local file instead.
set -u
HOOK_DIR="\$(cd "\$(dirname "\$0")" && pwd)"
LOCAL_HOOK="\$HOOK_DIR/$(basename "$hook").local"
PATH_PRIVACY_SCRIPT="$source_script"

# Run the pre-existing hook first, if any.
if [ -x "\$LOCAL_HOOK" ]; then
  "\$LOCAL_HOOK" "\$@" || exit \$?
fi

# Run path-privacy.
if [ -x "\$PATH_PRIVACY_SCRIPT" ]; then
  "\$PATH_PRIVACY_SCRIPT" "\$@" || exit \$?
fi
exit 0
EOF
  chmod +x "$hook"
  echo "installed $hook"
}

install_wrapper pre-commit "$SELF_DIR/git-pre-commit"
install_wrapper commit-msg "$SELF_DIR/git-commit-msg"

echo ""
echo "path-privacy hooks installed in $TARGET_REPO."
echo "To uninstall: $0 --uninstall"
