#!/usr/bin/env bash
# path-privacy: skip-file
# install-git-hooks.sh - install path-privacy git hooks into a repo.
#
# Default behavior: install pre-commit and commit-msg hooks that delegate to the
# scanner. If a hook already exists, the existing hook is preserved by being
# moved to <hook>.local and the new wrapper invokes it first, then runs the
# path-privacy check.
#
# Usage:
#   install-git-hooks.sh                      # install into the current repo
#   install-git-hooks.sh -C <path-to-repo>    # install into a different repo
#   install-git-hooks.sh --uninstall          # restore .local backups, remove wrappers

set -eu

TARGET_REPO=""
UNINSTALL=0

while [ $# -gt 0 ]; do
  case "$1" in
    -C|--cwd)       TARGET_REPO="$2"; shift 2 ;;
    --uninstall)    UNINSTALL=1; shift ;;
    -h|--help)      sed -n '2,12p' "$0"; exit 0 ;;
    *) echo "install-git-hooks: unknown arg: $1" >&2; exit 2 ;;
  esac
done

if [ -z "$TARGET_REPO" ]; then
  TARGET_REPO=$(git rev-parse --show-toplevel 2>/dev/null || echo "")
fi
# `.git` is a FILE in worktrees and submodules, so -d rejected them with a
# misleading "missing" message and no way to install.
if [ -z "$TARGET_REPO" ] || ! git -C "$TARGET_REPO" rev-parse --git-dir >/dev/null 2>&1; then
  echo "install-git-hooks: not a git repo: $TARGET_REPO" >&2
  exit 2
fi

# Honour core.hooksPath. Writing to .git/hooks in a repo that sets it produces a
# successful-looking install whose hooks git never runs -- every husky/lefthook
# repo, silently ungated. That is the exact fail-open the wrapper works hard to
# avoid, one level up, so it must not be silent here either.
CUSTOM_HOOKS_PATH=$(git -C "$TARGET_REPO" config --get core.hooksPath 2>/dev/null || echo "")
if [ -n "$CUSTOM_HOOKS_PATH" ]; then
  case "$CUSTOM_HOOKS_PATH" in
    /*) HOOKS_DIR="$CUSTOM_HOOKS_PATH" ;;
    *)  HOOKS_DIR="$TARGET_REPO/$CUSTOM_HOOKS_PATH" ;;
  esac
  echo "note: core.hooksPath is set; installing into $HOOKS_DIR (not .git/hooks)" >&2
else
  HOOKS_DIR="$TARGET_REPO/.git/hooks"
fi
mkdir -p "$HOOKS_DIR"

SELF_DIR="$(cd "$(dirname "$0")" && pwd)"

uninstall_one() {
  local name="$1"
  local hook="$HOOKS_DIR/$name"
  local backup="$hook.local"
  if [ -f "$backup" ]; then
    # If the live hook is neither ours nor the backup, the user has written their
    # own since installing. Restoring over it would silently destroy their work.
    if [ -f "$hook" ] && ! grep -q 'path-privacy:wrapper' "$hook" 2>/dev/null; then
      echo "install-git-hooks: $hook is not a path-privacy wrapper." >&2
      echo "  Leaving it alone. Your earlier hook is still at $backup." >&2
      return 0
    fi
    mv "$backup" "$hook"
    echo "restored $hook from $backup"
  elif [ -f "$hook" ] && grep -q 'path-privacy:wrapper' "$hook" 2>/dev/null; then
    rm -f "$hook"
    echo "removed $hook"
  else
    echo "no path-privacy wrapper at $hook (nothing to do)"
  fi
}

if [ $UNINSTALL -eq 1 ]; then
  uninstall_one pre-commit
  uninstall_one commit-msg
  exit 0
fi

install_wrapper() {
  local name="$1"          # pre-commit | commit-msg
  local source_script="$2" # absolute path to the path-privacy script
  local hook="$HOOKS_DIR/$name"
  local backup="$hook.local"

  # If an existing hook is present and is NOT a path-privacy wrapper, back it up.
  if [ -f "$hook" ] && ! grep -q 'path-privacy:wrapper' "$hook" 2>/dev/null; then
    if [ ! -f "$backup" ]; then
      cp "$hook" "$backup"
      chmod +x "$backup"
      echo "preserved existing $hook -> $backup"
    else
      # A .local already exists AND the live hook is not ours -- the user has
      # replaced it since. Overwriting with no copy anywhere loses their work.
      echo "install-git-hooks: $hook is not a path-privacy wrapper and $backup" >&2
      echo "  already exists. Refusing to overwrite; move or remove one of them." >&2
      exit 2
    fi
  fi

  # A hook can be a SYMLINK into the work tree (ln -s ../../scripts/pre-commit.sh
  # is a common pattern). `cat > "$hook"` follows it and writes the wrapper into
  # the user's tracked source file, which they may then commit. Replace the link
  # itself, never write through it. The backup above already captured contents.
  if [ -L "$hook" ]; then
    echo "replacing symlink $hook (target left untouched)"
    rm -f "$hook"
  fi

  cat > "$hook" <<EOF
#!/usr/bin/env bash
# path-privacy:wrapper -- generated by install-git-hooks.sh. Edit .local file instead.
set -u
HOOK_DIR="\$(cd "\$(dirname "\$0")" && pwd)"
HOOK_NAME="$(basename "$hook")"
LOCAL_HOOK="\$HOOK_DIR/\$HOOK_NAME.local"
SCRIPT_NAME="$(basename "$source_script")"
PATH_PRIVACY_SCRIPT="$source_script"

# Run the pre-existing hook first, if any.
if [ -x "\$LOCAL_HOOK" ]; then
  "\$LOCAL_HOOK" "\$@" || exit \$?
fi

# The path above is frozen at install time. For a marketplace install it points
# into the VERSION-STAMPED plugin cache: an update writes a new version dir and
# orphans the old one, deleted 14 days later, so the path dies on a 14-day fuse.
# Re-resolve to the newest copy. sort -V, not last-wins over glob order, which is
# lexicographic and would pick 0.1.9 over 0.1.10.
if [ ! -x "\$PATH_PRIVACY_SCRIPT" ]; then
  # Search the frozen path's own tree first, so a LOCAL checkout or --plugin-dir
  # install (whose scripts never live under the plugin cache) can still recover.
  FROZEN_ROOT="\${PATH_PRIVACY_SCRIPT%/skills/path-privacy/scripts/*}"
  # Highest version that is ACTUALLY EXECUTABLE, not merely highest. A newest
  # copy with the exec bit lost must not shadow a working older one and block
  # every commit.
  newest_exec() {
    printf '%s\\n' "\$@" | sort -rV | {
      while IFS= read -r c; do
        if [ -x "\$c" ]; then printf '%s' "\$c"; break; fi
      done
    }
  }
  # Groups are tried IN ORDER rather than merged. sort -V over a merged list
  # compares the marketplace directory before the version component, so a stale
  # copy under cache/zz-other/ outranks a newer one from your own tree.
  CAND="\$(newest_exec "\${FROZEN_ROOT%/*}"/*/skills/path-privacy/scripts/"\$SCRIPT_NAME")"
  [ -z "\$CAND" ] && CAND="\$(newest_exec "\$FROZEN_ROOT"/skills/path-privacy/scripts/"\$SCRIPT_NAME")"
  [ -z "\$CAND" ] && CAND="\$(newest_exec "\$HOME"/.claude/plugins/cache/*/path-privacy/*/skills/path-privacy/scripts/"\$SCRIPT_NAME")"
  [ -n "\$CAND" ] && PATH_PRIVACY_SCRIPT="\$CAND"
fi

# Fail CLOSED and loudly. This hook is a leak gate; if it cannot run, allowing
# the commit silently is the worst outcome -- that is how a gate becomes
# decorative without anyone noticing.
if [ ! -x "\$PATH_PRIVACY_SCRIPT" ]; then
  echo "path-privacy: scanner not found -- the leak gate is NOT running." >&2
  echo "" >&2
  echo "  Why now: this usually means the plugin was updated and the old cached" >&2
  echo "  copy has since been cleaned up. It fires on the next commit after that," >&2
  echo "  which is why it looks unrelated to what you are committing." >&2
  echo "" >&2
  echo "  Looked for: \$SCRIPT_NAME under" >&2
  echo "    \${FROZEN_ROOT:-<install dir>}/ and \$HOME/.claude/plugins/cache/*/path-privacy/*/" >&2
  echo "  Reinstall:  /path-privacy:path-privacy   (or re-run install-git-hooks.sh)" >&2
  if [ -f "\$LOCAL_HOOK" ]; then
    # This wrapper CHAINS your previous hook. Deleting it would silently drop
    # that hook too, so restore it rather than remove the wrapper.
    echo "  Remove:     mv \$LOCAL_HOOK \$HOOK_DIR/\$HOOK_NAME" >&2
    echo "              (restores the \$HOOK_NAME hook you had before path-privacy)" >&2
  else
    echo "  Remove:     rm \$HOOK_DIR/\$HOOK_NAME" >&2
  fi
  exit 1
fi

"\$PATH_PRIVACY_SCRIPT" "\$@" || exit \$?
exit 0
EOF
  chmod +x "$hook"
  echo "installed $hook"
}

install_wrapper pre-commit "$SELF_DIR/git-pre-commit"
install_wrapper commit-msg "$SELF_DIR/git-commit-msg"

echo ""
echo "path-privacy hooks installed in $TARGET_REPO."
echo "To uninstall: $0 --uninstall"
